version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: topupdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    env_file:
      - ./.env.example
    ports:
      - '3000:3000'
    depends_on:
      - db
  frontend:
    build: ./frontend
    command: npm run build && npm run preview --port 5173
    ports:
      - '5173:5173'
volumes:
  db_data:
